### ISSUE TITLE
Changing env definition

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#118]
Currently, environment variables are defined as -

```yaml
    env:
    - foo=bar
```

This limits the ability to extend the environment variables, like supporting secrets.

Let's change the environment variables definition to -

```yaml
    env:
    - name: foo
      value: bar
```
