### ISSUE TITLE
Change syntax for referencing higher value fields

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#119]
Currently, this is applicable only to 
The way root level volumes are referenced are -

```yaml
  containers:
    mounts:
    - volumeName: db
      mountPath: /app/store
      volumeSubPath: foo/bar
```

We should change the standard for such references to other higher level definitions to `<fieldname>Ref`, in this case, changing `volumeName` to `volumeRef` i.e.

```yaml
  containers:
    mounts:
    - volumeRef: db
      mountPath: /app/store
      volumeSubPath: foo/bar
```
