### ISSUE TITLE
Could services be a map?

### ISSUE THREAD

**Issue by joshwget** [redhat-developer/opencompose#146]
Any reason why the second syntax couldn't be used? Maybe it's a matter of preference, but I think a map would work well for this (also resembles Docker Compose a bit more).

```
version: 0.1-dev
services:
- name: helloworld
  containers:
  - image: tomaskral/nonroot-nginx
    ports:
    - port: 8080
```
```
version: 0.1-dev
services:
  helloworld:
    containers:
    - image: tomaskral/nonroot-nginx
      ports:
      - port: 8080
```

**Comment by concaf** [comment]
Hey @joshwget, we have had similar discussions on #105 and elsewhere, and we decided that the OpenCompose spec should take control of all the keys in the spec to maintain consistency and to allow extending fields.
e.g. - we recently refactored environment variables from -
```yaml
env:
- a=b
- x=y
```
to
```yaml
env:
- name: a
  value: b
- name: x
  secretRef: <secret>
```

The latter allows us to add more fields like referring to a secret in the env variable, without breaking the consistency, in the sense that, throughout the env definition, all the keys are in control of the spec.

Thoughts? Would love your input on this :)
