### ISSUE TITLE
container port exposed via multiple services results into invalid Deployment

### ISSUE THREAD

**Issue by kadel** [redhat-developer/opencompose#165]
```
version: 0.1-dev
services:
- name: helloworld
  containers:
  - image: quay.io/tomkral/nginx
    ports:
    - port: 8080:8080
      type: external
    - port: 8080:8088
      type: external
    - port: 8080:8090
```

Why you try convert opencompose file like this it results into multiple issues

1) Deployment is invalid. `Deployment.extensions "helloworld" is invalid: [spec.template.spec.containers[0].ports[1].name: Duplicate value: "port-8080", spec.template.spec.containers[0].ports[2].name: Duplicate value: "port-8080"]
`
2) It generates two services with same name
