### ISSUE TITLE
why is services a list/slice and not map

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/opencompose#78]
why are services as list

```yaml
services:
- name: database
  ...
- name: web
  ...
- name: cache
  ...
```

and not map, like this?

```yaml
services:
  database:
  ...
  web:
  ...
  cache:
  ...
```
