### ISSUE TITLE
opencompose generates deployment per container

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/opencompose#86]
I am using this opencompose file:

```yaml
version: 0.1-dev
services:
- name: helloworld
  containers:
  - image: tomaskral/nonroot-nginx
    ports:
    - port: 8080
  - image: hell
    ports:
    - port: 1111
```

When run i get error as follows:

```yaml
✔ ~/go/src/github.com/redhat-developer/opencompose/examples [master ↑·52|✚ 1] 
11:59 $ opencompose convert -f hello-nginx.yaml -o -
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: helloworld
  name: helloworld
spec:
  ports:
  - name: port-8080
    port: 8080
    targetPort: 8080
  - name: port-1111
    port: 1111
    targetPort: 1111
  selector:
    service: helloworld
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: helloworld
  name: helloworld
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: helloworld
    spec:
      containers:
      - image: tomaskral/nonroot-nginx
        name: helloworld-0
        ports:
        - containerPort: 8080
          name: port-8080
        resources: {}
      - image: hell
        name: helloworld-1
        ports:
        - containerPort: 1111
          name: port-1111
        resources: {}
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: helloworld
  name: helloworld
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: helloworld
    spec:
      containers:
      - image: tomaskral/nonroot-nginx
        name: helloworld-0
        ports:
        - containerPort: 8080
          name: port-8080
        resources: {}
      - image: hell
        name: helloworld-1
        ports:
        - containerPort: 1111
          name: port-1111
        resources: {}
status: {}
```

I think this was not discovered because we were only generating files and the file might have been over written.
