### ISSUE TITLE
`unset value` error is giving internal data structure names not the field value

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/opencompose#97]
I am getting this error for the opencompose file missing the `image` field
```bash
$ opencompose convert -f no-storage.yaml -o -
ERROR: could not unmarshal data for file 'no-storage.yaml': Required field "Image" has unset value ""
```

I am expecting an error like this 

```
ERROR: could not unmarshal data for file 'no-storage.yaml': Required field "image" has unset value ""
```
notice here the field name is not from the internal data structure but from the opencompose file.

The opencompose file I used was:

```yaml
version: '0.1-dev'

services:
- name: database
  containers:
  - env:
      - MYSQL_ROOT_PASSWORD=rootpasswd
```

@kadel this is similar issue we faced in kompose, where we needed a mapping of the opencompose objects to the internal data structures.
